version: "3.8"

services:
  backend:
    image: <ECR>/backend:latest
    restart: unless-stopped
    volumes:
      - ../db:/data
    environment:
      DB_PATH: /data/matrix.db
    ports:
      - "4000:4000"

  ai:
    image: <ECR>/ai:latest
    volumes:
      - ../db:/data
    environment:
      DB_PATH: /data/matrix.db

  frontend:
    image: <ECR>/frontend:latest
    ports:
      - "80:80"
