name: Backend CI

on:
  push:
    paths:
      - "services/backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-south-1

      - run: |
          docker build -t backend services/backend
          docker tag backend:latest ${{ secrets.ECR_BACKEND }}
          docker push ${{ secrets.ECR_BACKEND }}
